spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
